### PR TITLE
Readme additions

### PR DESCRIPTION
**Pull request by kilahimm**
add instructions for handling jars for full-text search indexing, add curl-dev library for passenger setup, add libreoffice for .doc & .docx derivative generation.

### CODE REVIEW

**Comment by kerchner** [comment]
@kilahimm why `mv /opt/solr/contrib/extraction /opt/solr/contrib/extraction_bak` as opposed to just deleting it?

**Comment by kilahimm** [comment]
@kerchner i figure it's safer then removing the existing jars all together.  In case we surface anything later on.

**Comment by kerchner** [comment]
@kilahimm if that were the case, we can always re-rake sufia:jetty:config  .   If any issues were to arise, they would most likely involve being a bit more precise about what we're doing here, particularly regarding solr versions etc.

**Comment by kilahimm** [comment]
@kerchner running rake wouldn't recreate the jars that ship with solr that we initially deploy into /opt/solr

**Comment by kerchner** [comment]
@kilahimm Wait a minute, I just realized something.  Aren't we talking about two different servers here, in a production setup?   Don't you have solr running on one server, and the app running on another?  Did you have to move the folder from one server to the other?  (Or did you have the app files set up on the solr server?)

**Comment by kilahimm** [comment]
@kerchner that is correct, but our readme is written for deploying the application and solr/fedora on a single server.

**Pull request merged**
