### PR TITLE
T69 citation

### LINKED ISSUE #69: Add Citation Feature Back and Link
Re-add /citation feature that was previously broken in Sufia and add link to generic_files view.

### PR DESCRIPTION
**Pull request by kilahimm**
Resolves #69 Created a "Cite" action.  This makes citation a more usable feature of the app.

### CODE REVIEW

**Comment by kilahimm** [comment]
requires 6.3.0 upgrade

**Comment by kerchner** [comment]
@kilahimm take a look:  https://github.com/projecthydra/sufia/pull/1281/files

**Comment by kilahimm** [comment]
@kerchner good catch, as you said going through sufia makes the most sense for this.  I'm going to close the PR, sound good?

**Comment by kerchner** [comment]
@kilahimm Yes if we can wait for the next Sufia release, into which projecthydra/sufia#1281 ought to be merged, then we can avoid overriding _show_actions.html.erb .  If you'd like to close this pull request, you can put a note in #69 that we can close #69 as soon as we take the next release of sufia to include projecthydra/sufia#1281 .

**Comment by kilahimm** [comment]
Closing this PR as there is a PR in Sufia that will implement this feature.

**Pull request closed without merging**
