### PR TITLE
Created rake task to populate content blocks from files under config/…

### LINKED ISSUE #28: Populate center grey region with initial marketing text
Since it appears this is data, not configuration, may wish to create a script that will populate initial data such as this, for a new deployment.

### PR DESCRIPTION
**Pull request by kerchner**
…locales/content_blocks. Fixes #28.

### CODE REVIEW

**Comment by kilahimm** [comment]
This checks out in my testing.  @kerchner should I ticket looking into how to handle historical featured researchers separately?

**Comment by kerchner** [comment]
@kilahimm I'm taking a look now to see how those work / look in the database tables, to determine if I need to modify this PR.

**Comment by kilahimm** [comment]
@kerchner OK i'll hold off on anything further with this PR until I hear back.

**Comment by kerchner** [comment]
@kilahimm This can now be reviewed/merged.   I've carved off #86 to address the part we're not doing in this release.

**Comment by kilahimm** [comment]
Testing looks good and confirmed with @kerchner this is good to merge.  Closing.

**Pull request merged**
